### ISSUE TITLE
Hard coded seed

### ISSUE THREAD

**Issue by nothingismagick** [Thoralf-M/tangleproof#3]
Please do not recommend this style:

https://github.com/Thoralf-M/tangleproof/blob/cc9a8bc53c82d8934d69fac1465bf2494b731d85/config.json#L5

It would be better to use a .env file at the very least.

**Comment by Thoralf-M** [comment]
You're right, I started with a .env file, but it didn't read hardened bip32paths correctly, but it's removed now so I can switch back

**Comment by Thoralf-M** [comment]
Changed it here https://github.com/Thoralf-M/tangleproof/commit/00318a0ef55513b30102552f12d2e9aadc4fe638
